-- Expand ideas from a single note into a persistent development workspace.

CREATE TABLE idea_entry (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idea_id    BIGINT NOT NULL REFERENCES idea(id) ON DELETE CASCADE,
    content    TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE idea_research (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idea_id    BIGINT NOT NULL REFERENCES idea(id) ON DELETE CASCADE,
    title      VARCHAR(200) NOT NULL,
    url        TEXT,
    type       VARCHAR(20) NOT NULL DEFAULT 'REFERENCE'
               CHECK (type IN ('REFERENCE','COMPETITOR','MARKET','INSPIRATION','OTHER')),
    notes      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE idea_task_link (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idea_id    BIGINT NOT NULL REFERENCES idea(id) ON DELETE CASCADE,
    entry_id   BIGINT REFERENCES idea_entry(id) ON DELETE SET NULL,
    task_id    BIGINT NOT NULL REFERENCES task(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_idea_entry_idea ON idea_entry (idea_id, created_at);
CREATE INDEX idx_idea_research_idea ON idea_research (idea_id, created_at);
CREATE INDEX idx_idea_task_link_idea ON idea_task_link (idea_id);
CREATE INDEX idx_idea_task_link_task ON idea_task_link (task_id);
