-- ===========================================================================
-- Compileme — V1: initial schema (PostgreSQL 16)
-- Enum benzeri alanlar VARCHAR + CHECK olarak tutulur (JPA @Enumerated(STRING)
-- ile uyumlu ve PG native enum'a göre değiştirmesi kolay).
-- ===========================================================================

-- ----------------------------- Kullanici -----------------------------------
CREATE TABLE app_user (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ----------------------------- Ayarlar -------------------------------------
CREATE TABLE settings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL UNIQUE REFERENCES app_user(id) ON DELETE CASCADE,
    water_goal_ml     INT          NOT NULL DEFAULT 3000,
    weather_city      VARCHAR(120) NOT NULL DEFAULT 'İstanbul',
    theme             VARCHAR(20)  NOT NULL DEFAULT 'DARK',
    focus_brightness  INT          NOT NULL DEFAULT 77,
    focus_temperature VARCHAR(20)  NOT NULL DEFAULT 'NEUTRAL'
);

-- ----------------------------- Projeler ------------------------------------
CREATE TABLE project (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    name        VARCHAR(200) NOT NULL,
    description TEXT,
    status      VARCHAR(20) NOT NULL DEFAULT 'PLANNING'
                CHECK (status IN ('PLANNING','ACTIVE','PAUSED','DONE')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE project_phase (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    name        VARCHAR(200) NOT NULL,
    description TEXT,
    status      VARCHAR(20) NOT NULL DEFAULT 'PLANNING'
                CHECK (status IN ('PLANNING','ACTIVE','PAUSED','DONE')),
    start_date  DATE,
    end_date    DATE,
    order_index INT NOT NULL DEFAULT 0
);

CREATE TABLE project_technology (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    category   VARCHAR(20) NOT NULL
               CHECK (category IN ('BACKEND','FRONTEND','MOBILE','DATABASE','DEVOPS','OTHER')),
    title      VARCHAR(200) NOT NULL,   -- ör. "API katmani"
    technology VARCHAR(200) NOT NULL,   -- ör. "Spring Boot"
    notes      TEXT,
    order_index INT NOT NULL DEFAULT 0
);

CREATE TABLE project_snippet (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    title       VARCHAR(200) NOT NULL,
    language    VARCHAR(40),
    code        TEXT NOT NULL,
    description TEXT,
    category    VARCHAR(20) NOT NULL DEFAULT 'OTHER'
                CHECK (category IN ('FRONTEND','BACKEND','OTHER')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE project_link (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    title      VARCHAR(200) NOT NULL,
    url        TEXT NOT NULL,
    type       VARCHAR(20) NOT NULL DEFAULT 'REFERENCE'
               CHECK (type IN ('DESIGN','REFERENCE','REPO','OTHER')),
    category   VARCHAR(20)
               CHECK (category IN ('FRONTEND','BACKEND','OTHER')),
    notes      TEXT,
    order_index INT NOT NULL DEFAULT 0
);

-- Teknik dokuman / DB semasi / refaktor plani / gelecek ozellikler / genel not
CREATE TABLE project_document (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id     BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    type           VARCHAR(20) NOT NULL
                   CHECK (type IN ('DB_SCHEMA','REFACTOR_PLAN','FUTURE_FEATURES','TECH_DOC','GENERAL')),
    title          VARCHAR(200) NOT NULL,
    content        TEXT,
    content_format VARCHAR(20) NOT NULL DEFAULT 'MARKDOWN'
                   CHECK (content_format IN ('MARKDOWN','CODE','SQL')),
    order_index    INT NOT NULL DEFAULT 0
);

-- ----------------------------- Fikirler ------------------------------------
CREATE TABLE idea (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    title               VARCHAR(200) NOT NULL,
    content             TEXT,
    status              VARCHAR(20) NOT NULL DEFAULT 'RAW'
                        CHECK (status IN ('RAW','DEVELOPING','CONVERTED')),
    tags                VARCHAR(300),
    converted_project_id BIGINT REFERENCES project(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----------------------------- Egitimler -----------------------------------
CREATE TABLE education (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    title            VARCHAR(200) NOT NULL,   -- ör. "Rust Programlama"
    source           VARCHAR(200),            -- ör. "The Rust Book"
    source_url       TEXT,
    type             VARCHAR(20) NOT NULL DEFAULT 'PROGRAMMING'
                     CHECK (type IN ('PROGRAMMING','LANGUAGE','OTHER')),
    progress_percent INT NOT NULL DEFAULT 0 CHECK (progress_percent BETWEEN 0 AND 100),
    status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                     CHECK (status IN ('ACTIVE','PAUSED','DONE')),
    next_study_date  DATE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE education_resource (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_id BIGINT NOT NULL REFERENCES education(id) ON DELETE CASCADE,
    name         VARCHAR(200) NOT NULL,
    type         VARCHAR(20) NOT NULL
                 CHECK (type IN ('PDF','SLIDE','FILE','LINK')),
    url_or_path  TEXT NOT NULL,
    order_index  INT NOT NULL DEFAULT 0
);

CREATE TABLE education_practice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    education_id BIGINT NOT NULL REFERENCES education(id) ON DELETE CASCADE,
    title        VARCHAR(200) NOT NULL,
    completed    BOOLEAN NOT NULL DEFAULT FALSE,
    code         TEXT,
    notes        TEXT,
    order_index  INT NOT NULL DEFAULT 0
);

-- ----------------------------- Gorevler ------------------------------------
-- Anasayfa (bugun/yarin), takvim ve faz gorevleri AYNI tabloyu kullanir.
CREATE TABLE task (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    title            VARCHAR(300) NOT NULL,
    notes            TEXT,
    status           VARCHAR(10) NOT NULL DEFAULT 'TODO'
                     CHECK (status IN ('TODO','DONE')),
    kind             VARCHAR(20) NOT NULL DEFAULT 'GENERAL'
                     CHECK (kind IN ('GENERAL','PROJECT','EDUCATION','REFACTOR')),
    scheduled_date   DATE,
    scheduled_time   TIME,
    duration_minutes INT,
    planning_bucket  VARCHAR(20) NOT NULL DEFAULT 'DAY'
                     CHECK (planning_bucket IN ('UNSCHEDULED','DAY','WEEK','MONTH')),
    target_period    VARCHAR(20),  -- hafta/ay etiketi, ör. "2026-06"
    project_id       BIGINT REFERENCES project(id) ON DELETE SET NULL,
    phase_id         BIGINT REFERENCES project_phase(id) ON DELETE SET NULL,
    education_id     BIGINT REFERENCES education(id) ON DELETE SET NULL,
    order_index      INT NOT NULL DEFAULT 0,
    completed_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----------------------------- Su takibi -----------------------------------
CREATE TABLE water_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    log_date   DATE NOT NULL DEFAULT CURRENT_DATE,
    amount_ml  INT NOT NULL CHECK (amount_ml > 0),
    source     VARCHAR(20) NOT NULL DEFAULT 'CUSTOM'
               CHECK (source IN ('BOTTLE_1500','HALF_500','GLASS_300','CUSTOM')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----------------------- Odak / ekran basi sure ----------------------------
CREATE TABLE focus_session (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    started_at       TIMESTAMPTZ NOT NULL,
    ended_at         TIMESTAMPTZ,
    duration_seconds INT,
    type             VARCHAR(20) NOT NULL DEFAULT 'FOCUS'
                     CHECK (type IN ('FOCUS','GENERAL')),
    session_date     DATE NOT NULL DEFAULT CURRENT_DATE
);

-- ----------------------------- Indeksler -----------------------------------
CREATE INDEX idx_task_user_date   ON task (user_id, scheduled_date);
CREATE INDEX idx_task_kind        ON task (kind);
CREATE INDEX idx_task_bucket      ON task (planning_bucket);
CREATE INDEX idx_task_project     ON task (project_id);
CREATE INDEX idx_task_phase       ON task (phase_id);
CREATE INDEX idx_task_education   ON task (education_id);
CREATE INDEX idx_phase_project    ON project_phase (project_id);
CREATE INDEX idx_water_user_date  ON water_log (user_id, log_date);
CREATE INDEX idx_focus_user_date  ON focus_session (user_id, session_date);
CREATE INDEX idx_edu_resource_edu ON education_resource (education_id);
CREATE INDEX idx_edu_practice_edu ON education_practice (education_id);
