-- ===========================================================================
-- Compileme — V3: stored_file table
-- Yüklenen dosyaların metaverilerini saklamak ve sahiplik kontrolü için.
-- ===========================================================================

CREATE TABLE stored_file (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    original_name VARCHAR(255) NOT NULL,
    stored_name   VARCHAR(255) NOT NULL UNIQUE,
    file_size     BIGINT NOT NULL,
    content_type  VARCHAR(100),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_stored_file_user ON stored_file (user_id);
